/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();

    }


//  @Test public void RestaurantConstTest() {
//    Restaurant restaurant = new Restaurant("Mariam", 5 ,90);
//    System.out.println("Restaurant: toSting: " + restaurant);
//    assertEquals("restaurant name should return 'Mariam'","Mariam", restaurant.getName());
//  }

}
